version: "3.2"
services:
     openmrs-db:
         build:
             context: ./mysql
         container_name: openmrs-db
         ports:
             - "3320:3306"
         networks:
             - network
         volumes:
             - datadb:/var/lib/mysql

     tomcat:
         build:
             context: ./tomcat
         container_name: tomcat
         ports:
             - "80:8080"
         networks:
             - network
         depends_on:
             - "openmrs-db"
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS
         healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 30s
            retries: 15
networks:
  network:
    driver: bridge

volumes:
  datadb:
