version: "3.2"
services:
     # Postgresql: Database shared by multiple services
     postgres:
         image: postgres:9.6-alpine
         environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            # OpenELIS DB Vars
            - OPENELIS_DB_USER=clinlims
            - OPENELIS_DB_PASSWORD=clinlims
            - OPENELIS_DB_NAME=clinlims
            # Odoo DB vars
            - ODOO_DB_NAME=odoo
            - ODOO_DB_USER=odoo
            - ODOO_DB_PASSWORD=Odoo123
         networks:
            - lafianet
         volumes:
            - postgresql-data:/var/lib/postgresql/data
            - "./data/postgresql:/docker-entrypoint-initdb.d"

     odoo:
         image: odoo:lafia3
         depends_on:
            - postgres
         ports:
            - "8069:8069"
         networks:
            - lafianet
         environment:
            - HOST=postgres
            - DB_NAME=odoo
            - USER=odoo
            - PASSWORD=Odoo123

     openelis:
         build:
             context: ./openelis
         ports:
            - "8073:8080"
         networks:
            - lafianet
         depends_on:
            - "postgres"
         environment:
            - OPENMRS_DB_SERVER=openmrs-db
            - OPENMRS_DB_USERNAME=root
            - OPENMRS_DB_PASSWORD=root
            - OPENELIS_DB_USER=clinlims
            - OPENELIS_DB_PASSWORD=clinlims
            - OPENELIS_DB_NAME=clinlims
            - ATOMFEED_PROPERTIES_FILE_PATH=/usr/local/tomcat/.OpenELIS/atomfeed.properties
            - HIBERNATE_PROPERTIES_FILE_PATH=/usr/local/tomcat/.OpenELIS/hibernate.properties
             
     openmrs-db:
         build:
             context: ./mysql
         ports:
             - "3320:3306"
         networks:
             - lafianet
         healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 30s
            retries: 15
         volumes:
             - openmrsdb:/var/lib/mysql

     openmrs:
         build:
             context: ./tomcat
         ports:
             - "8080:8080"
         networks:
             - lafianet
         depends_on:
             - "openmrs-db"
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS

     # Bahmni Apps: The main front-end component
     # Front END EMR
     lafiamed:
         image: bahmniapps:lafia1
         ports:
            - "8900:8900"
         healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost:8900/home/index.html"
            timeout: 20s
         networks:
            - lafianet
         volumes:
            - ./bahmni/lafiamed:/var/www

     # Bahmni Config: Bahmni Apps configuration
     lafiamed-config:
         image: httpd:2.4
         expose:
           - "8901"
         healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost:8901/openmrs/apps/home/app.json"
            timeout: 20s
         networks:
            - lafianet
         volumes:
            - ./properties/apache/httpd-8901.conf:/usr/local/apache2/conf/httpd.conf
            - ./bahmni/lafiamed_config:/var/www

     lafia-home:
         image: httpd:2.4
         expose:
            - "8904"
         healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost:8904/document_images/index.html"
            timeout: 20s
         depends_on:
            - openmrs
         networks:
            - lafianet
         volumes:
            - ./bahmni/lafia_home:/var/www/
            - ./properties/apache/httpd-8904.conf:/usr/local/apache2/conf/httpd.conf

    # Apache HTTPD: Entry point for the application.
     proxy:
         image: lafiaproxy:lafia1
         command: "httpd-foreground ${PROXY_TLS}"
         healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost/"
         networks:
            - lafianet
         ports:
            - "${PROXY_PUBLIC_PORT}:80"
            - "${PROXY_PUBLIC_PORT_TLS}:443"
         volumes:
            - "./proxy/confs:/usr/local/apache2/conf/extra"
            - "${PROXY_TLS_CERTS_PATH:-proxy-tls-certs}:/etc/tls"

networks:
  lafianet:
    driver: bridge

volumes:
  openmrsdb:
  postgresql-data:
  proxy-tls-certs: