version: "3.2"
services:
     # Postgresql: Database shared by multiple services
     postgres:
         image: postgres:9.6-alpine
         environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            # OpenELIS DB Vars
            - OPENELIS_DB_USER=clinlims
            - OPENELIS_DB_PASSWORD=clinlims
            - OPENELIS_DB_NAME=clinlims
            # Odoo DB vars
            - ODOO_DB_NAME=odoo
            - ODOO_DB_USER=odoo
            - ODOO_DB_PASSWORD=Odoo123
         networks:
            - lafianet
         volumes:
            - postgresql-data:/var/lib/postgresql/data
            - "./data/postgresql:/docker-entrypoint-initdb.d"

     odoo:
         image: odoo:lafia1
         depends_on:
            - postgres
         ports:
            - "8069:8069"
         networks:
            - lafianet
         environment:
            - HOST=postgres
            - DB_NAME=odoo
            - USER=odoo
            - PASSWORD=Odoo123

     openelis:
         build:
             context: ./openelis
         ports:
            - "8073:8080"
         networks:
            - lafianet
         depends_on:
            - "openmrs-db"
            - "postgres"
         environment:
            - OPENMRS_DB_SERVER=openmrs-db
            - OPENMRS_DB_USERNAME=root
            - OPENMRS_DB_PASSWORD=root
            - OPENELIS_DB_USER=clinlims
            - OPENELIS_DB_PASSWORD=clinlims
            - OPENELIS_DB_NAME=clinlims
            - ATOMFEED_PROPERTIES_FILE_PATH=/usr/local/tomcat/.OpenELIS/atomfeed.properties
            - HIBERNATE_PROPERTIES_FILE_PATH=/usr/local/tomcat/.OpenELIS/hibernate.properties
             
     openmrs-db:
         build:
             context: ./mysql
         ports:
             - "3320:3306"
         networks:
             - lafianet
         volumes:
             - openmrsdb:/var/lib/mysql

     openmrs:
         build:
             context: ./tomcat
         ports:
             - "80:8080"
         networks:
             - lafianet
         depends_on:
             - "openmrs-db"
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS
         healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 30s
            retries: 15

networks:
  lafianet:
    driver: bridge

volumes:
  openmrsdb:
  postgresql-data:
