version: "3.2"
services:
     odoo-db:
         image: postgres:9.6
         networks:
             - lafianet
         environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=Odoo123
            - POSTGRES_USER=odoo
         volumes:
             - odoo-data:/var/lib/postgresql/data 
    
     odoo-web:
         image: odoo:10
         depends_on:
            - odoo-db
         ports:
            - "8069:8069"
         networks:
            - lafianet
         environment:
            - HOST=odoo-db
            - USER=odoo
            - PASSWORD=Odoo123
         volumes:
           - type: bind
             source: ./data/odoo/addons
             target: /mnt/extra-addons

     openmrs-db:
         build:
             context: ./mysql
         ports:
             - "3320:3306"
         networks:
             - lafianet
         volumes:
             - datadb:/var/lib/mysql

     tomcat:
         build:
             context: ./tomcat
         ports:
             - "80:8080"
         networks:
             - lafianet
         depends_on:
             - "openmrs-db"
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS
         healthcheck:
            test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 30s
            retries: 15
networks:
  lafianet:
    driver: bridge

volumes:
  datadb:
  odoo-data:
